services:
  # Redis Service
  redis:
    image: redis:7.2-alpine 
    container_name: vault_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vault_network
    restart: always

  #ui cho reddis nhưng tự tìm phiên bản phù hợp đên khi chạy được
  redisinsight:
    image: redis/redisinsight:2.46
    container_name: vault_redis_ui
    user: root
    ports:
      - "8888:8001"
    networks:
      - vault_network
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
      - REDISINSIGHT_PORT=8001
    depends_on:
      - redis

networks:
  vault_network:
    driver: bridge

volumes:
  redis_data: