// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Đăng nhập bằng email và mật khẩu để nhận token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Xóa refresh token để đăng xuất",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng xuất",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.logoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin của người dùng đang đăng nhập",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Lấy thông tin cá nhân",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Lấy access token mới bằng refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Làm mới token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Đăng ký tài khoản mới bằng email và mật khẩu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/steam": {
            "get": {
                "description": "Chuyển hướng người dùng đến trang đăng nhập Steam OpenID",
                "tags": [
                    "Authentication (Steam)"
                ],
                "summary": "Đăng nhập bằng Steam",
                "responses": {
                    "302": {
                        "description": "Redirect"
                    }
                }
            }
        },
        "/auth/steam/callback": {
            "get": {
                "description": "Xử lý callback trả về từ Steam OpenID sau khi đăng nhập thành công",
                "tags": [
                    "Authentication (Steam)"
                ],
                "summary": "Steam Callback",
                "responses": {
                    "200": {
                        "description": "HTML Script trả về Frontend",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/rate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Đánh giá sao cho một game (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Đánh giá Game",
                "parameters": [
                    {
                        "description": "Thông tin đánh giá",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_RateGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/trending": {
            "get": {
                "description": "Lấy danh sách game phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Lấy danh sách game thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 12)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_GameTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{game_id}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thích hoặc Bỏ thích một game (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích Game",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Game",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/trending": {
            "get": {
                "description": "Lấy danh sách list phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Lấy danh sách List thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_ListTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{list_id}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thích hoặc Bỏ thích một list (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của List",
                        "name": "list_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reviews/trending": {
            "get": {
                "description": "Lấy danh sách review phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Lấy danh sách Review thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_ReviewTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reviews/{review_id}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Thích hoặc Bỏ thích một review (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích Review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin profile đầy đủ của người dùng (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Lấy Profile Người dùng",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ActivitySummary": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "preview": {
                    "type": "string"
                },
                "target_id": {
                    "type": "integer"
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.DiaryEntry": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/dto.GameSummary"
                },
                "logged_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "dto.GameSummary": {
            "type": "object",
            "properties": {
                "avg_rating": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_free": {
                    "type": "boolean"
                },
                "poster": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "review_count": {
                    "type": "integer"
                },
                "steam_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.GameTrendingResponse": {
            "type": "object",
            "properties": {
                "avg_rating": {
                    "type": "number"
                },
                "game_id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "studios": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_reviews": {
                    "type": "integer"
                },
                "trending_score": {
                    "type": "integer"
                }
            }
        },
        "dto.LikeGameResponse": {
            "type": "object",
            "properties": {
                "is_liked": {
                    "type": "boolean"
                }
            }
        },
        "dto.ListAuthorInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.ListTrendingResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.ListAuthorInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "game_count": {
                    "type": "integer"
                },
                "list_id": {
                    "type": "integer"
                },
                "thumbnails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "total_likes": {
                    "type": "integer"
                },
                "weekly_likes_count": {
                    "type": "integer"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_GameTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GameTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_ListTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ListTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_ReviewTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginationDTO": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "dto.RateGameRequest": {
            "type": "object",
            "required": [
                "game_id",
                "rating"
            ],
            "properties": {
                "game_id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0.5
                }
            }
        },
        "dto.RateGameResponse": {
            "type": "object",
            "properties": {
                "my_rating": {
                    "type": "number"
                },
                "new_game_avg": {
                    "type": "number"
                },
                "total_ratings": {
                    "type": "integer"
                }
            }
        },
        "dto.ReviewGameInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewSummary": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/dto.GameSummary"
                },
                "id": {
                    "type": "integer"
                },
                "img": {
                    "type": "string"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "recommend": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewTrendingResponse": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/dto.ReviewGameInfo"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "review_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/dto.ReviewUserInfo"
                }
            }
        },
        "dto.ReviewUserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.SuccessResponse-dto_AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.AuthResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_LikeGameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.LikeGameResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_RateGameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RateGameResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_UserProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserProfileResponse"
                }
            }
        },
        "dto.UserProfileResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "average_rating": {
                    "type": "number"
                },
                "backlog_games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GameSummary"
                    }
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "diary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DiaryEntry"
                    }
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "game_logs_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "list_count": {
                    "type": "integer"
                },
                "popular_reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewSummary"
                    }
                },
                "recent_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ActivitySummary"
                    }
                },
                "recent_reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewSummary"
                    }
                },
                "review_count": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.UserRole"
                },
                "steam_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "average_rating_count": {
                    "type": "number"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "game_logs_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "list_count": {
                    "type": "integer"
                },
                "review_count": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.UserRole"
                },
                "steam_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.logoutRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "handlers.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "handlers.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "models.UserRole": {
            "type": "string",
            "enum": [
                "user",
                "influencer",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleInfluencer",
                "RoleAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gaming Box API",
	Description:      "Hệ thống API cho Gaming Box.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
