// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/forgot-password": {
            "post": {
                "description": "Gửi yêu cầu khôi phục mật khẩu. (Luôn trả về thành công để bảo mật)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Quên mật khẩu",
                "parameters": [
                    {
                        "description": "Email đăng ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Đăng nhập bằng email và mật khẩu để nhận token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Xóa refresh token để đăng xuất",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng xuất",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.logoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Lấy thông tin của người dùng đang đăng nhập",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Lấy thông tin cá nhân",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Lấy access token mới bằng refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Làm mới token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.refreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Đăng ký tài khoản mới bằng email và mật khẩu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "post": {
                "description": "Đặt lại mật khẩu bằng token được cấp từ bước xác thực",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Đặt lại mật khẩu",
                "parameters": [
                    {
                        "description": "Thông tin đổi mật khẩu",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/steam": {
            "get": {
                "description": "Chuyển hướng người dùng đến trang đăng nhập Steam OpenID",
                "tags": [
                    "Authentication (Steam)"
                ],
                "summary": "Đăng nhập bằng Steam",
                "responses": {
                    "302": {
                        "description": "Redirect"
                    }
                }
            }
        },
        "/auth/steam/callback": {
            "get": {
                "description": "Xử lý callback trả về từ Steam OpenID sau khi đăng nhập thành công",
                "tags": [
                    "Authentication (Steam)"
                ],
                "summary": "Steam Callback",
                "responses": {
                    "200": {
                        "description": "HTML Script trả về Frontend",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/verify-code": {
            "post": {
                "description": "Xác thực mã 6 số gửi qua email để lấy token đổi mật khẩu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Xác thực mã khôi phục",
                "parameters": [
                    {
                        "description": "Mã xác thực",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_VerifyCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/popular": {
            "get": {
                "description": "Lấy danh sách game có đánh giá cao nhất",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Danh sách Game phổ biến",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 12,
                        "description": "Số lượng mỗi trang",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_GameTrendingResponse"
                        }
                    }
                }
            }
        },
        "/games/rate": {
            "post": {
                "description": "Đánh giá sao cho một game (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Đánh giá Game",
                "parameters": [
                    {
                        "description": "Thông tin đánh giá",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RateGameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_RateGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/games/search": {
            "get": {
                "description": "Tìm kiếm game theo tên có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Tìm kiếm Game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Từ khóa tìm kiếm",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 12,
                        "description": "Số lượng mỗi trang",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_GameTrendingResponse"
                        }
                    }
                }
            }
        },
        "/games/trending": {
            "get": {
                "description": "Lấy danh sách game phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Lấy danh sách game thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 12)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_GameTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/games/{game_id}/like": {
            "post": {
                "description": "Thích hoặc Bỏ thích một game (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích Game",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Game",
                        "name": "game_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/games/{id}": {
            "get": {
                "description": "Lấy thông tin đầy đủ của một game dựa trên ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Games"
                ],
                "summary": "Lấy chi tiết Game",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Game",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_GameDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists": {
            "post": {
                "description": "Tạo danh sách game cá nhân (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Tạo List mới",
                "parameters": [
                    {
                        "description": "Thông tin list",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateListRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_ListDetailResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/lists/trending": {
            "get": {
                "description": "Lấy danh sách list phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Lấy danh sách List thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_ListTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{id}": {
            "get": {
                "description": "Lấy thông tin và danh sách game trong một list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Xem chi tiết List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của List",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_ListDetailResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Chỉnh sửa thông tin hoặc danh sách game trong list (Chỉ chủ sở hữu)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Cập nhật List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của List",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_ListDetailResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Xóa một danh sách game (Chỉ chủ sở hữu)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lists"
                ],
                "summary": "Xóa List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của List",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-string"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/lists/{list_id}/like": {
            "post": {
                "description": "Thích hoặc Bỏ thích một list (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích List",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của List",
                        "name": "list_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications": {
            "get": {
                "description": "Lấy danh sách thông báo của người dùng hiện tại (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Lấy danh sách thông báo",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Số lượng hiển thị trên mỗi trang",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_NotificationResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications/read-all": {
            "post": {
                "description": "Đánh dấu tất cả thông báo của người dùng hiện tại là đã đọc",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Đánh dấu đã đọc tất cả thông báo",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/notifications/{id}/read": {
            "post": {
                "description": "Đánh dấu một thông báo cụ thể là đã đọc",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Đánh dấu đã đọc một thông báo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của thông báo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/reviews": {
            "post": {
                "description": "Tạo một review cho game (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Tạo Review mới",
                "parameters": [
                    {
                        "description": "Thông tin review",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_ReviewTrendingResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/reviews/trending": {
            "get": {
                "description": "Lấy danh sách review phổ biến có phân trang",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Lấy danh sách Review thịnh hành",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Trang hiện tại (Mặc định 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng mỗi trang (Mặc định 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_ReviewTrendingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reviews/{id}": {
            "put": {
                "description": "Chỉnh sửa review đã viết (Chỉ chủ sở hữu mới có quyền)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Cập nhật Review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_ReviewTrendingResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            },
            "delete": {
                "description": "Xóa một review (Chỉ chủ sở hữu)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Xóa Review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-string"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/reviews/{id}/comments": {
            "get": {
                "description": "Lấy tất cả bình luận của một review",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Lấy danh sách bình luận",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-array_dto_CommentResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Bình luận vào một review (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Thêm bình luận",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nội dung bình luận",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_CommentResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/reviews/{review_id}/like": {
            "post": {
                "description": "Thích hoặc Bỏ thích một review (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Thích hoặc Bỏ thích Review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Review",
                        "name": "review_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_LikeGameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/diary": {
            "get": {
                "description": "Lấy danh sách nhật ký chơi game của người dùng",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Xem Nhật ký chơi game",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID người dùng",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_DiaryEntry"
                        }
                    }
                }
            }
        },
        "/users/follow": {
            "post": {
                "description": "Thực hiện follow hoặc unfollow một người dùng khác (Cần đăng nhập)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Follow / Unfollow Người dùng khác",
                "parameters": [
                    {
                        "description": "Thông tin follow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FollowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_FollowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me": {
            "get": {
                "description": "Lấy thông tin profile đầy đủ của người dùng (Cần đăng nhập)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Lấy Profile Người dùng",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me/followers": {
            "get": {
                "description": "Lấy danh sách những người dùng đang follow current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Lấy danh sách người theo dõi",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Số lượng hiển thị trên mỗi trang",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_UserSummary"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/me/following": {
            "get": {
                "description": "Lấy danh sách những người dùng mà current user đang follow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Lấy danh sách đang theo dõi",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang hiện tại",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Số lượng hiển thị trên mỗi trang",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_UserSummary"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ]
            }
        },
        "/users/profile": {
            "get": {
                "description": "Lấy thông tin profile đầy đủ của một người dùng dựa theo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Xem Profile người dùng khác",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID của Người dùng",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/stats": {
            "get": {
                "description": "Xem thống kê về game đã chơi, đánh giá trung bình...",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Lấy thống kê người dùng",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID người dùng (Nếu không có sẽ lấy me)",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponse-dto_UserStatsResponse"
                        }
                    }
                }
            }
        },
        "/users/watchlist": {
            "get": {
                "description": "Lấy danh sách game muốn chơi của người dùng",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Xem Watchlist (Backlog)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID người dùng",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Trang",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Giới hạn",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PaginatedResponse-array_dto_GameSummary"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ActivitySummary": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "preview": {
                    "type": "string"
                },
                "target_id": {
                    "type": "integer"
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.CommentRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer"
                }
            }
        },
        "dto.CommentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/dto.ReviewUserInfo"
                }
            }
        },
        "dto.CreateListRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "game_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_public": {
                    "type": "boolean"
                },
                "thumbnail_img": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.CreateReviewRequest": {
            "type": "object",
            "required": [
                "content",
                "game_id",
                "recommend"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "game_id": {
                    "type": "integer"
                },
                "img": {
                    "type": "string"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "recommend": {
                    "type": "string",
                    "enum": [
                        "recommend",
                        "mixed",
                        "not_recommend"
                    ]
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.DiaryEntry": {
            "type": "object",
            "properties": {
                "game": {
                    "$ref": "#/definitions/dto.GameSummary"
                },
                "logged_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "dto.FollowRequest": {
            "type": "object",
            "required": [
                "userId"
            ],
            "properties": {
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dto.FollowResponse": {
            "type": "object",
            "properties": {
                "is_following": {
                    "type": "boolean"
                }
            }
        },
        "dto.ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.GameDetailResponse": {
            "type": "object",
            "properties": {
                "average_playtime": {
                    "type": "number"
                },
                "avg_rating": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GenreDTO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_free": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "platforms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PlatformDTO"
                    }
                },
                "price": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "review_count": {
                    "type": "integer"
                },
                "steam_id": {
                    "type": "integer"
                },
                "studio": {
                    "$ref": "#/definitions/dto.StudioDTO"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.GameSummary": {
            "type": "object",
            "properties": {
                "avg_rating": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "is_free": {
                    "type": "boolean"
                },
                "poster": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "release_date": {
                    "type": "string"
                },
                "review_count": {
                    "type": "integer"
                },
                "steam_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.GameTrendingResponse": {
            "type": "object",
            "properties": {
                "avg_rating": {
                    "type": "number"
                },
                "game_id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "studios": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_reviews": {
                    "type": "integer"
                },
                "trending_score": {
                    "type": "integer"
                }
            }
        },
        "dto.GenreDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.LikeGameResponse": {
            "type": "object",
            "properties": {
                "is_liked": {
                    "type": "boolean"
                }
            }
        },
        "dto.ListAuthorInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.ListDetailResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.ListAuthorInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "game_count": {
                    "type": "integer"
                },
                "games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ListEntryDTO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "like_count": {
                    "type": "integer"
                },
                "thumbnail_img": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ListEntryDTO": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ListTrendingResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.ListAuthorInfo"
                },
                "created_at": {
                    "type": "string"
                },
                "game_count": {
                    "type": "integer"
                },
                "list_id": {
                    "type": "integer"
                },
                "thumbnails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "total_likes": {
                    "type": "integer"
                },
                "weekly_likes_count": {
                    "type": "integer"
                }
            }
        },
        "dto.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.NotificationResponse": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_read": {
                    "type": "boolean"
                },
                "sender_id": {
                    "type": "integer"
                },
                "target_id": {
                    "type": "integer"
                },
                "target_type": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_DiaryEntry": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DiaryEntry"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_GameSummary": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GameSummary"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_GameTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GameTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_ListTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ListTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_NotificationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.NotificationResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_ReviewTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewTrendingResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginatedResponse-array_dto_UserSummary": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.UserSummary"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/dto.PaginationDTO"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.PaginationDTO": {
            "type": "object",
            "properties": {
                "current_page": {
                    "type": "integer"
                },
                "limit": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "dto.PlatformDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.RateGameRequest": {
            "type": "object",
            "required": [
                "game_id",
                "rating"
            ],
            "properties": {
                "game_id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0.5
                }
            }
        },
        "dto.RateGameResponse": {
            "type": "object",
            "properties": {
                "my_rating": {
                    "type": "number"
                },
                "new_game_avg": {
                    "type": "number"
                },
                "total_ratings": {
                    "type": "integer"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "reset_token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "reset_token": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewGameInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewSummary": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/dto.GameSummary"
                },
                "id": {
                    "type": "integer"
                },
                "img": {
                    "type": "string"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "recommend": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewTrendingResponse": {
            "type": "object",
            "properties": {
                "comment_count": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "game": {
                    "$ref": "#/definitions/dto.ReviewGameInfo"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "rating": {
                    "type": "number"
                },
                "review_id": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/dto.ReviewUserInfo"
                }
            }
        },
        "dto.ReviewUserInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.StudioDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.SuccessResponse-array_dto_CommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CommentResponse"
                    }
                }
            }
        },
        "dto.SuccessResponse-dto_AuthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.AuthResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_CommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CommentResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_FollowResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.FollowResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_GameDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.GameDetailResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_LikeGameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.LikeGameResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_ListDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ListDetailResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_RateGameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RateGameResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_ReviewTrendingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.ReviewTrendingResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_UserProfileResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserProfileResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_UserStatsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UserStatsResponse"
                }
            }
        },
        "dto.SuccessResponse-dto_VerifyCodeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.VerifyCodeResponse"
                }
            }
        },
        "dto.SuccessResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateListRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "game_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "is_public": {
                    "type": "boolean"
                },
                "thumbnail_img": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateReviewRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "img": {
                    "type": "string"
                },
                "is_spoiler": {
                    "type": "boolean"
                },
                "recommend": {
                    "type": "string",
                    "enum": [
                        "recommend",
                        "mixed",
                        "not_recommend"
                    ]
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.UserProfileResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "average_rating": {
                    "type": "number"
                },
                "backlog_games": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GameSummary"
                    }
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "diary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DiaryEntry"
                    }
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "game_logs_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "list_count": {
                    "type": "integer"
                },
                "popular_reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewSummary"
                    }
                },
                "recent_activity": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ActivitySummary"
                    }
                },
                "recent_reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewSummary"
                    }
                },
                "review_count": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.UserRole"
                },
                "steam_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "average_rating_count": {
                    "type": "number"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "follower_count": {
                    "type": "integer"
                },
                "following_count": {
                    "type": "integer"
                },
                "game_logs_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "list_count": {
                    "type": "integer"
                },
                "review_count": {
                    "type": "integer"
                },
                "role": {
                    "$ref": "#/definitions/models.UserRole"
                },
                "steam_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.UserStatsResponse": {
            "type": "object",
            "properties": {
                "average_rating": {
                    "type": "number"
                },
                "genre_distribution": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "rating_distribution": {
                    "description": "1 to 5 stars",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "total_played": {
                    "type": "integer"
                },
                "total_reviews": {
                    "type": "integer"
                }
            }
        },
        "dto.UserSummary": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.VerifyCodeResponse": {
            "type": "object",
            "properties": {
                "reset_token": {
                    "type": "string"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.logoutRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "handlers.refreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "handlers.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "models.UserRole": {
            "type": "string",
            "enum": [
                "user",
                "influencer",
                "admin"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleInfluencer",
                "RoleAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gaming Box API",
	Description:      "Hệ thống API cho Gaming Box.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
